version: "3"

services:
    mysqld:
        image: mysql:latest
        container_name: survey-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: heiwasurvey
            MYSQL_PORT: "3306"
        volumes:
            - mysql-data:/var/lib/mysql

    app:
        image: lenabett/heiwasurvey:latest
        ports:
            - "8080:8080"
        depends_on:
            - mysqld
        environment:
            MYSQL_HOST: mysqld
            
volumes:
    mysql-data: